import { encryptSecret, decryptSecret, hashSecret } from './connection-secrets';

const baseUrl=()=>String(process.env.UAZAPI_URL||'').replace(/\/$/,'');
async function call(path,options){if(!baseUrl())throw new Error('UAZAPI_URL não configurada na Vercel.');const response=await fetch(`${baseUrl()}${path}`,options);const text=await response.text();let data={};try{data=JSON.parse(text);}catch{}if(!response.ok)throw new Error(`UazAPI: ${response.status} ${data.message||text}`);return data;}
export async function createUazInstance(name){const adminToken=process.env.UAZAPI_ADMIN_TOKEN;if(!adminToken)throw new Error('Configure UAZAPI_ADMIN_TOKEN na Vercel para criar conexões UazAPI.');const data=await call('/instance/create',{method:'POST',headers:{admintoken:adminToken,'Content-Type':'application/json'},body:JSON.stringify({name})});if(!data.token)throw new Error('A UazAPI criou a instância, mas não retornou o token dela.');return {token:data.token,instanceName:data.instance?.name||data.name||name};}
export async function configureGlobalUazWebhook(){const base=String(process.env.WHATSENTREGAVEL_URL||'https://minifluxo.vercel.app').replace(/\/$/,'');const adminToken=process.env.UAZAPI_ADMIN_TOKEN;if(!adminToken)throw new Error('Configure UAZAPI_ADMIN_TOKEN na Vercel para registrar o webhook global da UazAPI.');await call('/globalwebhook',{method:'POST',headers:{admintoken:adminToken,'Content-Type':'application/json'},body:JSON.stringify({url:`${base}/api/webhooks/uazapi`,events:['messages','messages_update','connection'],excludeMessages:['isGroupYes'],addUrlEvents:false,addUrlTypesMessages:false})});}
export async function tokenForConnection(db,connection){let token;if(connection.uazapi_token_cipher)token=decryptSecret(connection.uazapi_token_cipher);else {const created=await createUazInstance(connection.instance_name||connection.name);token=created.token;await db.from('connections').update({instance_name:created.instanceName,uazapi_token_cipher:encryptSecret(token),uazapi_token_hash:hashSecret(token),status:'disconnected'}).eq('id',connection.id);}if(!connection.uazapi_token_hash)await db.from('connections').update({uazapi_token_hash:hashSecret(token)}).eq('id',connection.id);return token;}
export async function uazCall(token,path,body){return call(path,{method:'POST',headers:{token,'Content-Type':'application/json'},body:JSON.stringify(body)});}
export async function disconnectUazInstance(db,connection){return uazCall(await tokenForConnection(db,connection),'/instance/disconnect',{});}
export async function uazGet(token,path){return call(path,{headers:{token}});}
