import { NextResponse } from 'next/server';
import { adminClient, requireUser } from '../supabase';

export const dynamic='force-dynamic';
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
const isDeadlock = error => error?.code === '40P01' || /(?:40P01|deadlock)/i.test(error?.message || '');

export async function GET(){try{const user=await requireUser();const {data,error}=await adminClient().from('video_orders').select('*').eq('owner_id',user.id).order('created_at',{ascending:false}).limit(100);if(error)throw error;return NextResponse.json(data);}catch(error){return NextResponse.json({error:error.message||'Não autenticado.'},{status:401});}}
export async function POST(request){try{const user=await requireUser();const body=await request.json();const photos=Array.isArray(body.photos)?body.photos.map(value=>String(value).trim()).filter(Boolean):[];const privatePrefix=`storage://video-inputs/${user.id}/`;if(!body.audio_url||photos.length<4||photos.length>8||!body.lyrics?.trim())return NextResponse.json({error:'Informe um MP3, a letra e entre 4 e 8 fotos.'},{status:400});if(!String(body.audio_url).startsWith(privatePrefix)||photos.some(url=>!url.startsWith(privatePrefix)))return NextResponse.json({error:'Os arquivos precisam ser enviados pela sua conta antes de criar o vídeo.'},{status:400});const values={owner_id:user.id,order_id:body.order_id||null,audio_url:String(body.audio_url).trim(),photos,lyrics:String(body.lyrics).trim(),lyrics_timestamps:Array.isArray(body.lyrics_timestamps)?body.lyrics_timestamps:null,intro_text:body.intro_text?.trim()||null,status:'pending'};for(let attempt=0;attempt<3;attempt+=1){const {data,error}=await adminClient().from('video_orders').insert(values).select().single();if(!error)return NextResponse.json(data,{status:201});if(!isDeadlock(error)||attempt===2)throw error;await sleep(300*(attempt+1));}}catch(error){return NextResponse.json({error:error.message||'Não foi possível criar o vídeo.'},{status:500});}}
