'use client';

import { useEffect, useMemo, useState } from 'react';

const providerName=provider=>provider==='uazapi'?'API Não Oficial — UazAPI':'API Oficial — Meta';
const statusName=status=>({connected:'Conectada',connecting:'Conectando',disconnected:'Desconectada',hibernated:'Pausada'}[status]||status);
const date=value=>value?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'—';

export function ConnectionCreationModal({close,create,error}){
  return <div className="modal-wrap"><div className="connection-modal"><button className="close" onClick={close}>×</button><div className="connection-modal-title"><span>▯</span><h2>Nova Conexão</h2></div><form onSubmit={create}><label>Nome da Conexão *<input name="name" placeholder="Ex.: WhatsApp Vendas" required autoFocus/></label><fieldset className="provider-picker"><legend>Tipo de Conexão *</legend><label className="provider-option"><input type="radio" name="provider" value="uazapi" defaultChecked/><span className="provider-icon web">◉</span><b>API Web</b><small>(UazAPI)</small></label><label className="provider-option"><input type="radio" name="provider" value="meta"/><span className="provider-icon meta">∞</span><b>API Oficial</b><small>(Meta)</small></label></fieldset><div className="next-steps"><b>Próximos passos:</b><span>• A conexão será criada como <strong>Desconectada</strong></span><span>• Depois, escaneie o QR Code ou conecte pelo número de telefone.</span></div>{error&&<p className="form-error">{error}</p>}<div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancelar</button><button className="primary">Criar Conexão</button></div></form></div></div>;
}

export default function ConnectionsPanel({items,onConnectionsChange}){
  const [integration,setIntegration]=useState(null),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[qr,setQr]=useState(null),[pairTarget,setPairTarget]=useState(null),[phone,setPhone]=useState(''),[pairing,setPairing]=useState(null),[message,setMessage]=useState('');
  useEffect(()=>{fetch('/api/site-integration').then(r=>r.ok?r.json():null).then(setIntegration).catch(()=>{});},[]);
  const filtered=useMemo(()=>items.filter(item=>`${item.name} ${item.instance_name||''}`.toLowerCase().includes(search.toLowerCase())),[items,search]);
  const connected=items.filter(item=>item.status==='connected').length;
  const disconnected=items.filter(item=>item.status!=='connected').length;
  const setConnecting=id=>onConnectionsChange(items.map(item=>item.id===id?{...item,status:'connecting'}:item));
  async function useForSite(connectionId){setBusy(true);const r=await fetch('/api/site-integration',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({connection_id:connectionId})});const data=await r.json();if(r.ok)setIntegration(data);else setMessage(data.error||'Não foi possível selecionar a conexão.');setBusy(false);}
  async function changeProvider(id,provider){setMessage('');const r=await fetch(`/api/connections/${id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({provider})});const data=await r.json();if(!r.ok)return setMessage(data.error||'Não foi possível alterar a conexão.');onConnectionsChange(items.map(item=>item.id===id?data:item));setMessage('Conexão alterada para API Não Oficial — UazAPI. Agora escolha QR Code ou Pair Code.');}
  async function openQr(id){setMessage('');const r=await fetch(`/api/connections/${id}/qr`,{method:'POST'});const data=await r.json();if(!r.ok)return setMessage(data.error||'Não foi possível gerar o QR Code.');if(!data.qr)return setMessage('A UazAPI não retornou um QR Code para esta instância.');setConnecting(id);setQr({id,value:data.qr});}
  async function requestPairing(event){event.preventDefault();setMessage('');const r=await fetch(`/api/connections/${pairTarget}/pairing`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({phone:`55${phone}`})});const data=await r.json();if(!r.ok)return setMessage(data.error||'Não foi possível gerar o código.');setConnecting(pairTarget);setPairing(data);}
  return <section className="connections-page"><div className="connections-banner"><div><span className="section-icon">▯</span><b>Conexões</b></div><small>Conecte seus números e escolha qual WhatsApp será usado pelo site.</small></div><div className="site-integration-note"><div><b>Integração do seu site</b><small>Chave fixa da sua conta: <code>WHATSENTREGAVEL_INTEGRATION_KEY={integration?.integration_key||'Carregando...'}</code></small></div><small>WhatsApp atual: <b>{items.find(item=>item.id===integration?.connection_id)?.name||'Escolha uma conexão abaixo'}</b></small></div><div className="connection-metrics"><Metric label="Conectadas" value={connected} tone="green"/><Metric label="Desconectadas" value={disconnected} tone="red"/><Metric label="Slots disponíveis" value={`${items.length} / ∞`} tone="purple"/></div><div className="connections-table-card"><label className="connection-search"><span>⌕</span><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Busque por nome ou número da instância"/></label><div className="connections-table"><div className="connection-row connection-head"><span>CONEXÃO</span><span>TIPO</span><span>STATUS</span><span>CRIADA EM</span><span>AÇÕES</span></div>{filtered.length?filtered.map(item=><div className="connection-row" key={item.id}><div className="connection-name"><span className="phone-icon">▯</span><div><b>{item.name}</b><small>{item.instance_name||'Sem telefone'}</small></div></div><span className={`provider-tag ${item.provider}`}>{item.provider==='uazapi'?'UAZAPI':'META'}</span><span className={`connection-status ${item.status}`}>{statusName(item.status)}</span><small>{date(item.created_at)}</small><div className="connection-row-actions">{item.provider==='uazapi'?<><button onClick={()=>openQr(item.id)} title="QR Code"><span>⌘</span><small>QRCODE</small></button><button onClick={()=>{setPairTarget(item.id);setPairing(null);setPhone('');}} title="Código de pareamento"><span>▯</span><small>PAIRCODE</small></button></>:<button className="switch-uazapi" onClick={()=>changeProvider(item.id,'uazapi')}>Usar UazAPI</button>}<button className="use-site" disabled={busy||integration?.connection_id===item.id} onClick={()=>useForSite(item.id)}>{integration?.connection_id===item.id?'No site':'Usar no site'}</button></div></div>):<div className="empty">Nenhuma conexão encontrada.</div>}</div></div>{message&&<div className="toast">{message}</div>}{qr&&<QrModal qr={qr.value} refresh={()=>openQr(qr.id)} close={()=>setQr(null)}/>} {pairTarget&&<PairingModal phone={phone} setPhone={setPhone} pairing={pairing} submit={requestPairing} qr={()=>{setPairTarget(null);openQr(pairTarget)}} close={()=>setPairTarget(null)}/>}</section>;
}

function Metric({label,value,tone}){return <article className="connection-metric"><small>{label}</small><b>{value}</b><i className={tone}/></article>}
function QrModal({qr,refresh,close}){const source=qr.startsWith('data:')?qr:`data:image/png;base64,${qr}`;return <div className="modal-wrap"><div className="connect-modal"><button className="close" onClick={close}>×</button><div className="connection-modal-title"><span>⌘</span><h2>Conectar WhatsApp</h2></div><img className="qr qr-large" src={source} alt="QR Code para conectar WhatsApp"/><div className="qr-warning"><b>⚠ Importante</b><span>O WhatsApp invalida o QR Code a cada 20 segundos. Se expirar, atualize para gerar um novo.</span></div><div className="modal-actions"><button className="secondary" onClick={refresh}>⟳ Atualizar QR Code</button><button className="primary" onClick={close}>Fechar</button></div></div></div>}
function PairingModal({phone,setPhone,pairing,submit,qr,close}){return <div className="modal-wrap"><div className="connect-modal"><button className="close" onClick={close}>×</button><div className="connection-modal-title"><span>▯</span><h2>Conectar WhatsApp</h2></div>{pairing?<div className="pair-code-result"><small>No WhatsApp, abra <b>Aparelhos conectados</b> → <b>Conectar com número de telefone</b> e informe:</small><b>{pairing.code}</b><small>Esse código é temporário.</small></div>:<form onSubmit={submit}><label>Número de Telefone *<div className="pair-phone"><span>BR +55</span><input value={phone} onChange={event=>setPhone(event.target.value.replace(/\D/g,''))} placeholder="número sem +55" required/></div><small>Digite seu número sem o +55, apenas dígitos.</small></label><div className="modal-actions"><button type="button" className="secondary" onClick={qr}>Usar QR Code</button><button className="primary">Obter Código</button></div></form>}{pairing&&<div className="modal-actions"><button className="secondary" onClick={qr}>Usar QR Code</button><button className="primary" onClick={close}>Fechar</button></div>}</div></div>}
