'use client';

import { useEffect, useMemo, useState } from 'react';

const statusName=status=>({connected:'Conectada',connecting:'Conectando',disconnected:'Desconectada',hibernated:'Pausada'}[status]||status);
const date=value=>value?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'-';

export function ConnectionCreationModal({close,create,error}){
  return <div className="modal-wrap"><div className="connection-modal"><button className="close" onClick={close}>x</button><div className="connection-modal-title"><span>∞</span><h2>Canal oficial</h2></div><form onSubmit={create}><input type="hidden" name="provider" value="meta"/><label>Nome da conexão *<input name="name" placeholder="Ex.: WhatsApp Vendas" required autoFocus/></label><div className="next-steps"><b>API Oficial da Meta</b><span>- O canal é operado pela Datafy configurada na Vercel.</span><span>- Não há QR Code nem pareamento por aparelho.</span></div>{error&&<p className="form-error">{error}</p>}<div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancelar</button><button className="primary">Criar conexão</button></div></form></div></div>;
}

export default function ConnectionsPanel({items,onConnectionsChange}){
  const [integration,setIntegration]=useState(null);const [search,setSearch]=useState('');const [busy,setBusy]=useState(false);const [deletingId,setDeletingId]=useState(null);const [menuId,setMenuId]=useState(null);const [message,setMessage]=useState('');
  useEffect(()=>{fetch('/api/site-integration').then(response=>response.ok?response.json():null).then(setIntegration).catch(()=>{});},[]);
  const officialItems=items.filter(item=>item.provider==='meta');const filtered=useMemo(()=>officialItems.filter(item=>`${item.name} ${item.instance_name||''}`.toLowerCase().includes(search.toLowerCase())),[officialItems,search]);const connected=officialItems.filter(item=>item.status==='connected').length;const disconnected=officialItems.filter(item=>item.status!=='connected').length;
  async function useForSite(connectionId){setBusy(true);const response=await fetch('/api/site-integration',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({connection_id:connectionId})});const data=await response.json();if(response.ok)setIntegration(data);else setMessage(data.error||'Nao foi possivel selecionar a conexao.');setBusy(false);}
  async function deleteConnection(item){if(!window.confirm(`Excluir a conexao "${item.name}"? O WhatsApp sera desconectado na UazAPI.`))return;setMenuId(null);setMessage('');setDeletingId(item.id);const response=await fetch(`/api/connections/${item.id}`,{method:'DELETE'});if(!response.ok){const data=await response.json();setMessage(data.error||'Nao foi possivel excluir a conexao.');setDeletingId(null);return;}onConnectionsChange(previous=>previous.filter(connection=>connection.id!==item.id));if(integration?.connection_id===item.id)setIntegration(current=>({...current,connection_id:null}));setDeletingId(null);setMessage('Conexao excluida e WhatsApp desconectado.');}
  return <section className="connections-page"><div className="connections-banner"><div><span className="section-icon">∞</span><b>Canais oficiais</b></div><small>Todos os fluxos e todas as versões do site usam a API Oficial da Meta.</small></div><div className="site-integration-note"><div><b>Integração do seu site</b><small>Chave fixa da sua conta: <code>WHATSENTREGAVEL_INTEGRATION_KEY={integration?.integration_key||'Carregando...'}</code></small></div><small>Canal atual: <b>{officialItems.find(item=>item.id===integration?.connection_id)?.name||'Escolha um canal oficial abaixo'}</b></small></div><div className="connection-metrics"><Metric label="Conectados" value={connected} tone="green"/><Metric label="Indisponíveis" value={disconnected} tone="red"/><Metric label="Canais oficiais" value={officialItems.length} tone="purple"/></div><div className="connections-table-card"><label className="connection-search"><span>⌕</span><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Busque pelo canal oficial"/></label><div className="connections-table"><div className="connection-row connection-head"><span>CANAL</span><span>TIPO</span><span>STATUS</span><span>CRIADO EM</span><span>AÇÕES</span></div>{filtered.length?filtered.map(item=><div className="connection-row" key={item.id}><div className="connection-name"><span className="phone-icon">∞</span><div><b>{item.name}</b><small>{item.instance_name||'Canal oficial via Datafy'}</small></div></div><span className={`provider-tag ${item.provider}`}>META</span><span className={`connection-status ${item.status}`}>{statusName(item.status)}</span><small>{date(item.created_at)}</small><div className="connection-row-actions"><button className="use-site" disabled={busy||integration?.connection_id===item.id||item.status!=='connected'} onClick={()=>useForSite(item.id)}>{integration?.connection_id===item.id?'No site':'Usar no site'}</button><div className="connection-more"><button className="more-actions" onClick={()=>setMenuId(menuId===item.id?null:item.id)} aria-label="Mais ações">⋮</button>{menuId===item.id&&<div className="connection-menu"><button disabled={deletingId===item.id} onClick={()=>deleteConnection(item)}>{deletingId===item.id?'Excluindo...':'Excluir conexão'}</button></div>}</div></div></div>):<div className="empty">Nenhum canal oficial encontrado.</div>}</div></div>{message&&<div className="toast">{message}</div>}</section>;
}

function Metric({label,value,tone}){return <article className="connection-metric"><small>{label}</small><b>{value}</b><i className={tone}/></article>}
function QrModal({qr,refresh,close}){const source=qr.startsWith('data:')?qr:`data:image/png;base64,${qr}`;return <div className="modal-wrap"><div className="connect-modal"><button className="close" onClick={close}>x</button><div className="connection-modal-title"><span>⌘</span><h2>Conectar WhatsApp</h2></div><img className="qr qr-large" src={source} alt="QR Code para conectar WhatsApp"/><div className="qr-warning"><b>Importante</b><span>O WhatsApp invalida o QR Code a cada 20 segundos. Se expirar, atualize para gerar um novo.</span></div><div className="modal-actions"><button className="secondary" onClick={refresh}>Atualizar QR Code</button><button className="primary" onClick={close}>Fechar</button></div></div></div>}
function PairingModal({phone,setPhone,pairing,submit,qr,close}){return <div className="modal-wrap"><div className="connect-modal"><button className="close" onClick={close}>x</button><div className="connection-modal-title"><span>▯</span><h2>Conectar WhatsApp</h2></div>{pairing?<div className="pair-code-result"><small>No WhatsApp, abra <b>Aparelhos conectados</b> e informe:</small><b>{pairing.code}</b><small>Esse codigo e temporario.</small></div>:<form onSubmit={submit}><label>Numero de telefone *<div className="pair-phone"><span>BR +55</span><input value={phone} onChange={event=>setPhone(event.target.value.replace(/\D/g,''))} placeholder="numero sem +55" required/></div><small>Digite o numero sem +55, apenas digitos.</small></label><div className="modal-actions"><button type="button" className="secondary" onClick={qr}>Usar QR Code</button><button className="primary">Obter codigo</button></div></form>}{pairing&&<div className="modal-actions"><button className="secondary" onClick={qr}>Usar QR Code</button><button className="primary" onClick={close}>Fechar</button></div>}</div></div>}
