'use client';
import {useEffect,useMemo,useRef,useState} from 'react';

const time=value=>value?new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit'}).format(new Date(value)):'';
const preview=item=>{const last=item.messages?.at(-1);return last?.text||'Conversa iniciada pelo fluxo';};
export default function LiveChat(){
 const [items,setItems]=useState([]),[selectedId,setSelectedId]=useState(''),[query,setQuery]=useState(''),[text,setText]=useState(''),[loading,setLoading]=useState(true),[sending,setSending]=useState(false),[error,setError]=useState('');const bottom=useRef(null);
 const load=async(silent=false)=>{try{const r=await fetch('/api/chat',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setItems(d.conversations||[]);setSelectedId(current=>current||(d.conversations?.[0]?.id||''));}catch(e){if(!silent)setError(e.message)}finally{if(!silent)setLoading(false)}};
 useEffect(()=>{load();const id=window.setInterval(()=>load(true),5000);return()=>window.clearInterval(id)},[]);
 const visible=useMemo(()=>items.filter(item=>`${item.name} ${item.phone}`.toLowerCase().includes(query.toLowerCase())),[items,query]);const selected=items.find(item=>item.id===selectedId)||visible[0];
 useEffect(()=>{bottom.current?.scrollIntoView({block:'end'})},[selectedId,selected?.messages?.length]);
 async function send(e){e.preventDefault();if(!selected||!text.trim()||sending)return;setSending(true);setError('');try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lead_id:selected.id,text})});const d=await r.json();if(!r.ok)throw new Error(d.error);setItems(old=>old.map(item=>item.id===d.conversation.id?d.conversation:item));setText('');}catch(e){setError(e.message)}finally{setSending(false)}}
 if(loading)return <section className="chat-shell"><div className="empty"><p>Carregando conversas…</p></div></section>;
 return <section className="chat-shell"><aside className="chat-list"><div className="chat-list-head"><div><p className="eyebrow">API OFICIAL</p><h2>Conversas ao vivo</h2></div><span>{items.length}</span></div><input aria-label="Buscar conversa" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar nome ou WhatsApp"/>{visible.map(item=><button key={item.id} className={`chat-contact ${selected?.id===item.id?'selected':''}`} onClick={()=>setSelectedId(item.id)}><b>{item.name||'Cliente WhatsApp'}</b><small>+{item.phone}</small><p>{preview(item)}</p><time>{time(item.updated_at)}</time></button>)}{!visible.length&&<div className="empty"><p>Nenhuma conversa encontrada.</p></div>}</aside><div className="chat-thread">{selected?<><header className="chat-thread-head"><div className="avatar">{(selected.name||'C')[0]}</div><div><h2>{selected.name||'Cliente WhatsApp'}</h2><small>+{selected.phone} · {selected.status?.replaceAll('_',' ')}</small></div><span className="live-dot">Ao vivo</span></header><div className="chat-messages">{selected.messages?.map(message=><div key={message.id} className={`bubble ${message.direction==='in'?'incoming':'outgoing'}`}><p>{message.type==='text'?message.text:`${message.type} enviado`}</p><time>{time(message.created_at)}</time></div>)}{!selected.messages?.length&&<div className="empty"><p>As próximas mensagens desta conversa aparecerão aqui.</p></div>}<div ref={bottom}/></div><form className="chat-compose" onSubmit={send}><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Digite sua mensagem…" rows="2"/><button className="primary" disabled={sending||!text.trim()}>{sending?'Enviando…':'Enviar'}</button></form></>:<div className="empty"><p>Selecione uma conversa.</p></div>}{error&&<p className="chat-error">{error}</p>}</div></section>
}
