'use client';
import { useEffect, useMemo, useState } from 'react';
import FlowCanvas from './flow-canvas';
const labels={waiting_pix:'Aguardando Pix',waiting_briefing:'Aguardando briefing',generating:'Gerando musica',completed:'Entregue'};

export default function Dashboard({userEmail,initialLeads,initialConnections,initialFlows,initialDispatchConfigs}){
 const [tab,setTab]=useState('dashboard'),[leads,setLeads]=useState(initialLeads),[connections,setConnections]=useState(initialConnections),[flows,setFlows]=useState(initialFlows),[configs,setConfigs]=useState(initialDispatchConfigs),[selected,setSelected]=useState(initialFlows[0]||null),[modal,setModal]=useState(''),[qr,setQr]=useState(null),[error,setError]=useState(''),[origin,setOrigin]=useState('https://minifluxo.vercel.app');
 useEffect(()=>setOrigin(window.location.origin),[]);const connected=connections.find(x=>x.status==='connected');const metrics=useMemo(()=>({total:leads.length,waiting:leads.filter(x=>x.status!=='completed').length,complete:leads.filter(x=>x.status==='completed').length}),[leads]);
 async function submit(url,event,done){event.preventDefault();setError('');const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))}),data=await r.json();if(!r.ok)return setError(data.error);done(data)}
 const createFlow=e=>submit('/api/flows',e,x=>{setFlows([x,...flows]);setSelected(x);setModal('');setTab('flow')});const createLead=e=>submit('/api/leads',e,x=>{setLeads([x,...leads]);setModal('')});const createConnection=e=>submit('/api/connections',e,x=>{setConnections([...connections,x]);setModal('')});const saveConfig=e=>submit('/api/dispatch-config',e,x=>{setConfigs([...configs.filter(y=>y.connection_id!==x.connection_id),x]);setError('Configuracao salva.')});
 async function requestQr(id){const r=await fetch(`/api/connections/${id}/qr`,{method:'POST'}),d=await r.json();if(!r.ok)return setError(d.error);if(d.qr)setQr(d.qr)}
 const title=tab==='flow'?selected?.name:({dashboard:'Dashboard',flows:'Fluxos',connections:'Conexoes',leads:'Atendimentos',dispatches:'Disparos',webhooks:'Webhooks'}[tab]);
 return <div className="shell"><aside className="side"><div className="brand"><div className="mark">W</div><span>Whats<span>Entregavel</span></span></div><nav>{[['dashboard','Dashboard'],['flows','Fluxos'],['connections','Conexoes'],['leads','Atendimentos'],['dispatches','Disparos'],['webhooks','Webhooks']].map(([id,text])=><button key={id} className={tab===id||tab==='flow'&&id==='flows'?'active':''} onClick={()=>setTab(id)}>{text}</button>)}</nav><div className="side-foot"><div className={'dot '+(connected?'online':'')}/><small>{connected?`Conectado: ${connected.name}`:'WhatsApp desconectado'}</small></div></aside><main className="content"><header><div><p className="eyebrow">PAINEL OPERACIONAL</p><h1>{title}</h1></div><div className="head-actions"><span className="account">{userEmail}</span>{tab==='flows'&&<button className="primary" onClick={()=>setModal('flow')}>+ Novo fluxo</button>}{tab==='leads'&&<button className="primary" onClick={()=>setModal('lead')}>+ Novo contato</button>}{tab==='connections'&&<button className="primary" onClick={()=>setModal('connection')}>+ Conectar WhatsApp</button>}</div></header>{tab==='dashboard'&&<DashboardHome metrics={metrics} flows={flows} open={()=>setTab('flows')}/>} {tab==='flows'&&<Flows flows={flows} open={x=>{setSelected(x);setTab('flow')}} create={()=>setModal('flow')}/>} {tab==='flow'&&(selected?<FlowCanvas flow={selected}/>:<Empty text="Crie seu primeiro fluxo."/>)} {tab==='leads'&&<Leads leads={leads}/>} {tab==='connections'&&<Connections items={connections} qr={requestQr}/>} {tab==='dispatches'&&<Dispatches connections={connections} flows={flows} configs={configs} save={saveConfig}/>} {tab==='webhooks'&&<Webhooks origin={origin} connections={connections}/>}</main>{modal==='flow'&&<Modal title="Novo fluxo" close={()=>setModal('')} error={error}><form onSubmit={createFlow}><label>Nome do fluxo<input name="name" required/></label><label>Descricao<input name="description"/></label><button className="primary">Criar fluxo</button></form></Modal>}{modal==='lead'&&<Modal title="Iniciar contato" close={()=>setModal('')} error={error}><form onSubmit={createLead}><label>Nome<input name="name" required/></label><label>WhatsApp com DDI<input name="phone" required/></label><button className="primary">Enviar mensagem</button></form></Modal>}{modal==='connection'&&<Modal title="Conectar WhatsApp" close={()=>setModal('')} error={error}><form onSubmit={createConnection}><label>Nome<input name="name" required/></label><label>Provedor<select name="provider"><option value="meta">WhatsApp oficial</option><option value="uazapi">UazAPI</option></select></label><label>Identificador<input name="instance_name"/></label><button className="primary">Salvar conexao</button></form></Modal>}{qr&&<Modal title="Escaneie o QR Code" close={()=>setQr(null)}><img className="qr" src={qr.startsWith('data:')?qr:`data:image/png;base64,${qr}`} alt="QR Code"/></Modal>}{error&&!modal&&<div className="toast">{error}</div>}</div>
}
function DashboardHome({metrics,flows,open}){return <><section className="metrics"><Metric label="Atendimentos" value={metrics.total}/><Metric label="Em andamento" value={metrics.waiting}/><Metric label="Entregues" value={metrics.complete}/><Metric label="Fluxos" value={flows.length}/></section><section className="table-card"><div className="table-head"><h2>Seus fluxos</h2><button className="link" onClick={open}>Ver fluxos</button></div>{flows.length?<div className="lead-list">{flows.slice(0,3).map(x=><article className="lead-row" key={x.id}><div className="avatar">F</div><div><b>{x.name}</b><small>{x.description||'Fluxo de entrega'}</small></div></article>)}</div>:<Empty text="Crie seu primeiro fluxo."/>}</section></>}
function Flows({flows,open,create}){return <section className="flows-list">{flows.map(x=><button className="flow-card" key={x.id} onClick={()=>open(x)}><span className="flow-dot active"/><b>{x.name}</b><small>{x.description||'Fluxo de entrega musical'}</small><footer>{x.status==='active'?'ATIVO':'PAUSADO'} <i>{'>'}</i></footer></button>)}<button className="new-flow-card" onClick={create}><strong>+</strong><b>Novo fluxo</b><small>Crie uma automacao no canvas</small></button></section>}
function Connections({items,qr}){const[integration,setIntegration]=useState(null),[busy,setBusy]=useState(false);useEffect(()=>{fetch('/api/site-integration').then(r=>r.ok?r.json():null).then(setIntegration).catch(()=>{});},[]);async function useForSite(connectionId){setBusy(true);const r=await fetch('/api/site-integration',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({connection_id:connectionId})});const d=await r.json();if(r.ok)setIntegration(d);setBusy(false)}return <section className="connection-grid"><article className="saved-connection"><div><b>Integracao do seu site</b><small>Esta chave e fixa para sua conta. Copie uma unica vez para o ambiente do seu site.</small><small>WHATSENTREGAVEL_INTEGRATION_KEY={integration?.integration_key||'Carregando...'}</small><small>WhatsApp atual: {items.find(x=>x.id===integration?.connection_id)?.name||'Escolha abaixo'}</small></div></article>{items.map(x=><article className="saved-connection" key={x.id}><div className={'dot '+(x.status==='connected'?'online':'')}/><div><b>{x.name}</b><small>{x.provider} - {x.status}</small>{integration?.connection_id===x.id&&<small>Usado pelos pedidos do site</small>}</div><div>{x.provider==='uazapi'&&<button className="link qr-action" onClick={()=>qr(x.id)}>Gerar QR Code</button>}<button className="link qr-action" disabled={busy||integration?.connection_id===x.id} onClick={()=>useForSite(x.id)}>{integration?.connection_id===x.id?'WhatsApp do site':'Usar no site'}</button></div></article>)}</section>}
function Dispatches({connections,flows,configs,save}){if(!connections.length)return <Empty text="Crie uma conexao WhatsApp antes de configurar disparos."/>;return <section className="dispatch-list">{connections.map(c=>{const config=configs.find(x=>x.connection_id===c.id)||{};return <form key={c.id} className="dispatch-card" onSubmit={save}><input type="hidden" name="connection_id" value={c.id}/><div className="dispatch-title"><div className="avatar">W</div><div><h2>{c.name}</h2><small>{c.provider} - configure os gatilhos deste numero</small></div></div><label>Fluxo para pagamento aprovado<select name="payment_flow_id" defaultValue={config.payment_flow_id||''}><option value="">Nao disparar</option>{flows.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><small>Inicia quando o gateway confirmar o pagamento.</small></label><label>Fluxo para pedido vindo do site<select name="site_flow_id" defaultValue={config.site_flow_id||''}><option value="">Nao disparar</option>{flows.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><small>Inicia quando seu site enviar nome, numero e pedido musical.</small></label><button className="primary">Salvar disparos</button></form>})}</section>}
function Webhooks({origin,connections}){const connectionId=connections[0]?.id||'ID_DA_CONEXAO';return <section className="webhook-grid"><article className="webhook-card"><p className="eyebrow">PAGAMENTO APROVADO</p><h2>Webhook de pagamento</h2><p>O fluxo sera escolhido na aba Disparos pelo numero/conexao.</p><label>URL<input readOnly value={`${origin}/api/webhooks/payment`}/></label><label>Header<input readOnly value="x-payment-secret: seu PAYMENT_WEBHOOK_SECRET"/></label></article><article className="webhook-card"><p className="eyebrow">EXEMPLO</p><pre>{JSON.stringify({event:'PAYMENT_APPROVED',connection_id:connectionId,customer:{name:'Ana Martins',phone:'5511999999999'},music_request:'Musica romantica'},null,2)}</pre></article></section>}
function Leads({leads}){return <section className="table-card"><div className="table-head"><h2>Ultimos atendimentos</h2></div>{leads.length?<div className="lead-list">{leads.map(x=><article key={x.id} className="lead-row"><div className="avatar">{x.name[0]}</div><div><b>{x.name}</b><small>+{x.phone} - {x.source}</small></div><span className={'status '+x.status}>{labels[x.status]||x.status}</span></article>)}</div>:<Empty text="Nenhum atendimento."/>}</section>}
function Metric({label,value}){return <article className="metric"><small>{label}</small><b>{value}</b></article>}function Empty({text}){return <div className="empty"><p>{text}</p></div>}function Modal({title,close,error,children}){return <div className="modal-wrap"><div className="modal"><button className="close" onClick={close}>x</button><p className="eyebrow">WHATSENTREGAVEL</p><h2>{title}</h2>{error&&<p className="form-error">{error}</p>}{children}</div></div>}
